version: "3.8"

services:

  api-letmeask:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-letmeask
    restart: always
    env_file:
      - .env
    depends_on:
     - database-sql
     - database-nosql
     - queue
    ports:
      - 3333:3333

  database-sql:
    image: mariadb
    container_name: maria-db-api-letmeask
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadb

  database-nosql:
    image: mongo:4.4.6
    container_name: mongo-db-api-letmeask
    restart: always
    ports:
      - 27017:27017

  queue:
    image: "rabbitmq:3.8-management-alpine"
    container_name: queue-api-letmeask
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin